version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
      - build-312
      - build-310
      - build-38
      - build-37
      - build-36
      - build-27

jobs:
  build-312:
    docker:
      - image: cimg/python:3.12
      - image: cimg/postgres:14.18-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-312-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project simple_backup
            mkdir django
            cd django
            django-admin startproject sm
            mv ../simple_backup sm
            cd sm
            cp simple_backup/circle_settings.py sm/settings.py
            python manage.py migrate
            python manage.py test
            cp simple_backup/.pylintrc .
            pylint simple_backup
            bandit -r .
      - save_cache:
          key: venv-312-{{ .Branch }}-{{ checksum "/home/circleci/django/sm/simple_backup/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build-310:
    docker:
      - image: cimg/python:3.10
      - image: cimg/postgres:14.18-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-310-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project simple_backup
            mkdir django
            cd django
            django-admin startproject sm
            mv ../simple_backup sm
            cd sm
            cp simple_backup/circle_settings.py sm/settings.py
            python manage.py migrate
            python manage.py test
            cp simple_backup/.pylintrc .
            pylint simple_backup
            bandit -r .
      - save_cache:
          key: venv-310-{{ .Branch }}-{{ checksum "/home/circleci/django/sm/simple_backup/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build-38:
    docker:
      - image: cimg/python:3.8
      - image: cimg/postgres:12.18-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project simple_backup
            mkdir django
            cd django
            django-admin startproject sm
            mv ../simple_backup sm
            cd sm
            cp simple_backup/circle_settings.py sm/settings.py
            python manage.py migrate
            python manage.py test
            cp simple_backup/.pylintrc .
            pylint simple_backup
            bandit -r .
      - save_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "/home/circleci/django/sm/simple_backup/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build-37:
    docker:
      - image: cimg/python:3.7
      - image: cimg/postgres:12.18-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-37-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project simple_backup
            mkdir django
            cd django
            django-admin startproject sm
            mv ../simple_backup sm
            cd sm
            cp simple_backup/circle_settings.py sm/settings.py
            python manage.py migrate
            python manage.py test
            cp simple_backup/.pylintrc .
            pylint simple_backup
            bandit -r .
      - save_cache:
          key: venv-37-{{ .Branch }}-{{ checksum "/home/circleci/django/sm/simple_backup/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build-36:
    docker:
      - image: cimg/python:3.6
      - image: cimg/postgres:12.18-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-36-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project simple_backup
            mkdir django
            cd django
            django-admin startproject sm
            mv ../simple_backup sm
            cd sm
            cp simple_backup/circle_settings.py sm/settings.py
            python manage.py migrate
            python manage.py test
            cp simple_backup/.pylintrc .
            pylint simple_backup
            bandit -r .
      - save_cache:
          key: venv-36-{{ .Branch }}-{{ checksum "/home/circleci/django/sm/simple_backup/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build-27:
    docker:
      - image: cimg/python:2.7
      - image: cimg/postgres:9.6-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: venv-27-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            virtualenv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt --progress-bar off
            cd ..
            mv project simple_backup
            mkdir django
            cd django
            django-admin.py startproject sm
            mv ../simple_backup sm
            cd sm
            cp simple_backup/circle_settings.py sm/settings.py
            python manage.py migrate
            python manage.py test
            cp simple_backup/.pylintrc .
            pylint simple_backup
            bandit -r .
      - save_cache:
          key: venv-27-{{ .Branch }}-{{ checksum "/home/circleci/django/sm/simple_backup/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app
